config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'

  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]

  respond_to :html, :json

  def index
    @messages = Message.order(created_at: :desc).limit(21)
  end

  def new
    @message = Message.new
    respond_modal_with @message
  end

  def edit
    respond_modal_with @message
  end

  def update
    @message.update(message_params)
    respond_modal_with @message, location: messages_path
  end

  def create
    @message = Message.create(message_params)
    respond_modal_with @message, location: messages_path
  end

  def destroy
    @message.destroy
    redirect_to messages_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container justify-content-between">
    <%= link_to 'Remote Modals Demo', root_path, class: 'navbar-brand' %>

    <%= link_to 'Add Message', new_message_path, class: 'btn btn-outline-success my-2 my-sm-0', data: { modal: true } %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Remote Modals Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class=container>
      <%= yield %>
    </div>
    <div id='modal-holder'></div>
  </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= yield %>
    </div>
  </div>
</div>

app/views/messages/_form.html.erb
<%= simple_form_for(@message, remote: request.xhr?, html: { data: { modal: true } }) do |f| %>
  <div class="modal-body">
    <%= f.input :name %>
    <%= f.input :body %>
  </div>

  <div class="modal-footer">
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="card border-secondary mb-3">
  <div class="card-header d-flex justify-content-between">
    <%= message.name.truncate(20) %>
    <div class="d-flex justify-content-end">
      <%= link_to 'Edit', edit_message_path(message), class: 'mr-4', data: { modal: true } %>
      <%= link_to message, data: { confirm: 'Are you sure?' }, method: :delete, class: 'text-dark' do %>
        <span aria-hidden="true">&times;</span>
      <% end %>
    </div>
  </div>
  <div class="card-body text-secondary">
    <p class="card-text">
      <%= message.body %>
    </p>
  </div>
</div>

app/views/messages/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Edit message</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', message: @message %>

app/views/messages/index.html.erb
<h1>Messages</h1>

<div class="card-columns">
  <%= render @messages %>
</div>

app/views/messages/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">New message</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', message: @message %>